export const categoryColors: { [key: string]: any } = {
  smartphones: "primary",
  laptops: "secondary",
  fragrances: "error",
  skincare: "warning",
  groceries: "info",
  homeDecoration: "success",
  furniture: "customYellow",
  tops: "customPurple",
  womensDresses: "customOrange",
  womensShoes: "customPink",
  mensShirts: "primary",
  mensShoes: "secondary",
  mensWatches: "error",
  womensWatches: "warning",
  womensBags: "info",
  womensJewellery: "success",
  sunglasses: "customYellow",
  automotive: "customPurple",
  motorcycle: "customOrange",
  lighting: "customPink",
};
